#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := eth2wifi

EXTRA_COMPONENT_DIRS := $(abspath ../bsp)

EXCLUDE_COMPONENTS := fatfs libsodium

include $(IDF_PATH)/make/project.mk

