#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := eth2wifi

EXTRA_COMPONENT_DIRS := $(abspath ../bsp)

# CFLAGS += -DLWIP_NETIF_STATUS_CALLBACK=1

include $(IDF_PATH)/make/project.mk

