#############################################################################
# Generated by PAGE version 4.5
# in conjunction with Tcl version 8.6
#    Jun 22, 2018 11:45:34 AM


set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #111111
#############################################################################
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top37
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    set site_4_0 .top37.tNo38.pg0 
    set site_4_0 $site_4_0
    set site_4_1 .top37.tNo38.pg1 
    set site_4_0 $site_4_1
    set site_5_0 $site_4_0.tLa37
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# USER DEFINED PROCEDURES
#

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top37 {base} {
    if {$base == ""} {
        set base .top37
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 603x581+292+128
    update
    # set in toplevel.wgt.
    global vTcl
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1684 1032
    wm minsize $top 126 10
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    wm title $top "New Toplevel 1"
    vTcl:DefineAlias "$top" "GUI" vTcl:Toplevel:WidgetProc "" 1
    ttk::style configure TNotebook -background #d9d9d9
    ttk::style configure TNotebook.Tab -background #d9d9d9
    ttk::style configure TNotebook.Tab -foreground #000000
    ttk::style configure TNotebook.Tab -font TkDefaultFont
    ttk::style map TNotebook.Tab -background [list disabled #d9d9d9 selected #d9d9d9]
    ttk::notebook $top.tNo38 \
        -width 569 -height 506 -takefocus {} 
    vTcl:DefineAlias "$top.tNo38" "TNotebook1" vTcl:WidgetProc "GUI" 1
    frame .top37.tNo38.pg0 -background #d9d9d9
    $top.tNo38 add .top37.tNo38.pg0 \
        -padding 0 -sticky nsew -state normal -text Seriale -image {} \
        -compound none -underline -1 
    set site_4_0  $top.tNo38.pg0
    entry $site_4_0.ent40 \
        -background white -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black -justify center \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable portaSeriale 
    vTcl:DefineAlias "$site_4_0.ent40" "Entry1" vTcl:WidgetProc "GUI" 1
    button $site_4_0.but41 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command self.apriSeriale \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text {Usa questa} 
    vTcl:DefineAlias "$site_4_0.but41" "Button1" vTcl:WidgetProc "GUI" 1
    button $site_4_0.but37 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command self.apriFTDI \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text {Usa FTDI} 
    vTcl:DefineAlias "$site_4_0.but37" "Button47" vTcl:WidgetProc "GUI" 1
    button $site_4_0.but38 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command self.apriSocket \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text TCP 
    vTcl:DefineAlias "$site_4_0.but38" "Button4" vTcl:WidgetProc "GUI" 1
    entry $site_4_0.cpd39 \
        -background white -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black -justify center \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable indirizzoIP 
    vTcl:DefineAlias "$site_4_0.cpd39" "Entry4" vTcl:WidgetProc "GUI" 1
    place $site_4_0.ent40 \
        -in $site_4_0 -x 130 -y 110 -width 390 -height 25 -anchor nw \
        -bordermode ignore 
    place $site_4_0.but41 \
        -in $site_4_0 -x 30 -y 110 -width 80 -height 25 -anchor nw \
        -bordermode ignore 
    place $site_4_0.but37 \
        -in $site_4_0 -x 30 -y 165 -width 80 -height 25 -anchor nw \
        -bordermode ignore 
    place $site_4_0.but38 \
        -in $site_4_0 -x 30 -y 215 -width 82 -height 24 -anchor nw \
        -bordermode ignore 
    place $site_4_0.cpd39 \
        -in $site_4_0 -x 130 -y 215 -width 199 -height 25 -anchor nw \
        -bordermode inside 
    frame .top37.tNo38.pg1 -background #d9d9d9
    $top.tNo38 add .top37.tNo38.pg1 \
        -padding 0 -sticky nsew -state normal -text Varie -image {} \
        -compound none -underline -1 
    set site_4_1  $top.tNo38.pg1
    button $site_4_1.but37 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command self.Eco -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text Eco 
    vTcl:DefineAlias "$site_4_1.but37" "Button2" vTcl:WidgetProc "GUI" 1
    ttk::style configure TLabelframe.Label -background #d9d9d9
    ttk::style configure TLabelframe.Label -foreground #000000
    ttk::style configure TLabelframe.Label -font TkDefaultFont
    ttk::style configure TLabelframe -background #d9d9d9
    ttk::labelframe $site_4_1.tLa37 \
        -text Echi -width 230 -height 210 
    vTcl:DefineAlias "$site_4_1.tLa37" "TLabelframe1" vTcl:WidgetProc "GUI" 1
    set site_5_0 $site_4_1.tLa37
    label $site_5_0.lab39 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text Invia 
    vTcl:DefineAlias "$site_5_0.lab39" "Label2" vTcl:WidgetProc "GUI" 1
    entry $site_5_0.ent40 \
        -background white -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black -justify center \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable numEco 
    vTcl:DefineAlias "$site_5_0.ent40" "Entry2" vTcl:WidgetProc "GUI" 1
    button $site_5_0.but41 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text Esegui 
    vTcl:DefineAlias "$site_5_0.but41" "Button3" vTcl:WidgetProc "GUI" 1
    bind $site_5_0.but41 <ButtonRelease-1> {
        self.ecoProva
    }
    ttk::progressbar $site_5_0.tPr43 \
        -mode indeterminate 
    vTcl:DefineAlias "$site_5_0.tPr43" "TProgressbar1" vTcl:WidgetProc "GUI" 1
    label $site_5_0.lab37 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text pacchetti 
    vTcl:DefineAlias "$site_5_0.lab37" "Label3" vTcl:WidgetProc "GUI" 1
    label $site_5_0.lab38 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text da 
    vTcl:DefineAlias "$site_5_0.lab38" "Label4" vTcl:WidgetProc "GUI" 1
    entry $site_5_0.ent39 \
        -background white -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black -justify center \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable dimEco 
    vTcl:DefineAlias "$site_5_0.ent39" "Entry3" vTcl:WidgetProc "GUI" 1
    label $site_5_0.lab40 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text byte 
    vTcl:DefineAlias "$site_5_0.lab40" "Label5" vTcl:WidgetProc "GUI" 1
    place $site_5_0.lab39 \
        -in $site_5_0 -x 20 -y 25 -width 39 -height 25 -anchor nw \
        -bordermode ignore 
    place $site_5_0.ent40 \
        -in $site_5_0 -x 75 -y 25 -width 69 -height 25 -anchor nw \
        -bordermode ignore 
    place $site_5_0.but41 \
        -in $site_5_0 -x 70 -y 115 -width 90 -height 25 -anchor nw \
        -bordermode ignore 
    place $site_5_0.tPr43 \
        -in $site_5_0 -x 25 -y 160 -width 180 -height 22 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab37 \
        -in $site_5_0 -x 155 -y 25 -anchor nw -bordermode ignore 
    place $site_5_0.lab38 \
        -in $site_5_0 -x 35 -y 70 -width 29 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_5_0.ent39 \
        -in $site_5_0 -x 75 -y 65 -width 69 -height 25 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab40 \
        -in $site_5_0 -x 160 -y 70 -anchor nw -bordermode ignore 
    place $site_4_1.but37 \
        -in $site_4_1 -x 30 -y 25 -width 50 -height 25 -anchor nw \
        -bordermode ignore 
    place $site_4_1.tLa37 \
        -in $site_4_1 -x 100 -y 10 -width 230 -height 210 -anchor nw \
        -bordermode ignore 
    label $top.lab39 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -textvariable Messaggio 
    vTcl:DefineAlias "$top.lab39" "Label1" vTcl:WidgetProc "GUI" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tNo38 \
        -in $top -x 15 -y 45 -width 569 -height 506 -anchor nw \
        -bordermode ignore 
    place $top.lab39 \
        -in $top -x 20 -y 10 -width 559 -height 21 -anchor nw \
        -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

Window show .
Window show .top37

