#! /usr/bin/env python
#
# Support module generated by PAGE version 4.5
# In conjunction with Tcl version 8.6
#    Jun 27, 2018 11:36:33 AM


import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

def set_Tk_var():
    # These are Tk variables used passed to Tkinter and must be
    # defined before the widgets using them are created.
    global portaSeriale
    portaSeriale = StringVar()

    global indirizzoIP
    indirizzoIP = StringVar()

    global numEco
    numEco = StringVar()

    global dimEco
    dimEco = StringVar()

    global cp
    cp = StringVar()

    global cs
    cs = StringVar()

    global tst
    tst = StringVar()

    global cavo
    cavo = StringVar()

    global Messaggio
    Messaggio = StringVar()


def init(top, gui, arg=None):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None


